config/routes.rb
Rails.application.routes.draw do

  get 'comments/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'subreddits#front'
  get ':name', to: 'profiles#show', as: :profile
  resources :subreddits, only: [:new, :create, :show, :destroy] do
      resources :posts, only: [:new, :create, :show, :destroy] do
          resources :comments, only: [:index, :create, :destroy]
      end
  end
  
=begin
                  Prefix Verb   URI Pattern                                                     Controller#Action
        new_user_session GET    /users/sign_in(.:format)                                        devise/sessions#new
            user_session POST   /users/sign_in(.:format)                                        devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                                       devise/sessions#destroy
           user_password POST   /users/password(.:format)                                       devise/passwords#create
       new_user_password GET    /users/password/new(.:format)                                   devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)                                  devise/passwords#edit
                         PATCH  /users/password(.:format)                                       devise/passwords#update
                         PUT    /users/password(.:format)                                       devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                                         registrations#cancel
       user_registration POST   /users(.:format)                                                registrations#create
   new_user_registration GET    /users/sign_up(.:format)                                        registrations#new
  edit_user_registration GET    /users/edit(.:format)                                           registrations#edit
                         PATCH  /users(.:format)                                                registrations#update
                         PUT    /users(.:format)                                                registrations#update
                         DELETE /users(.:format)                                                registrations#destroy
                    root GET    /                                                               subreddits#front
                 profile GET    /:name(.:format)                                                profiles#show
 subreddit_post_comments GET    /subreddits/:subreddit_id/posts/:post_id/comments(.:format)     comments#index
                         POST   /subreddits/:subreddit_id/posts/:post_id/comments(.:format)     comments#create
  subreddit_post_comment DELETE /subreddits/:subreddit_id/posts/:post_id/comments/:id(.:format) comments#destroy
         subreddit_posts POST   /subreddits/:subreddit_id/posts(.:format)                       posts#create
      new_subreddit_post GET    /subreddits/:subreddit_id/posts/new(.:format)                   posts#new
          subreddit_post GET    /subreddits/:subreddit_id/posts/:id(.:format)                   posts#show
                         DELETE /subreddits/:subreddit_id/posts/:id(.:format)                   posts#destroy
              subreddits POST   /subreddits(.:format)                                           subreddits#create
           new_subreddit GET    /subreddits/new(.:format)                                       subreddits#new
               subreddit GET    /subreddits/:id(.:format)                                       subreddits#show
                         DELETE /subreddits/:id(.:format)                                       subreddits#destroy
=end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :comment_description, presence: true, length: { maximum: 400 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :subreddit
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { in: 1..50 }
  validates :url, presence: true, length: { maximum: 140 }, format: { without: /\A[h]t{2}[p]:{1}\D{2}/, message: "Take the http:// out of the url"}
end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
    belongs_to :user
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    validates :sub_name, presence: true, length: { in: 1..10 }
    validates :description, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { in: 1..15 }
  has_many :subreddits, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  
  def index
    @comments = Comment.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  
 
  def new
    @subreddit = Subreddit.find(params[:subreddit_id])
  end
  
  def create
    @subreddit = Subreddit.find(params[:subreddit_id])
    @post = @subreddit.posts.build(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      flash[:success] = "Your post was created."
      redirect_to subreddit_path(@subreddit)
    else
      render :new
    end
  end
  
  def destroy
    @subreddit = Subreddit.find(params[:subreddit_id])
    @post = @subreddit.posts.find(params[:id])
    unless current_user == @post.user
        flash[:alert] = "This post doesn't belong to you!"
        redirect_to root_path
    end
    @post.destroy
    flash[:success] = "Post destroyed."
    redirect_to subreddit_path(@subreddit)
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :url)
    end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = User.find_by(name: params[:name])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :owned_subreddit, only: [:destroy]
  
  def front
    @subreddits = Subreddit.all
  end
  
  def new
    @subreddit = current_user.subreddits.build
  end
  
  def create
    @subreddit = current_user.subreddits.build(subreddit_params)
    if @subreddit.save
      flash[:success] = "Subreddit Created!"
      redirect_to @subreddit
    else
      render :new
    end
  end

  def show
    @subreddit = Subreddit.find(params[:id])
  end
  
  def destroy
    @subreddit = Subreddit.find(params[:id])
    @subreddit.destroy
    flash[:success] = "Subreddit destroyed."
    redirect_to root_path
  end
  
  private
  
  def subreddit_params
    params.require(:subreddit).permit(:sub_name, :description)
  end
  
    def owned_subreddit
      unless current_user == @subreddit.user
        flash[:alert] = "This subreddit doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/comments/index.html.erb
<h1>Comments</h1>

<ul>
    <% @comments.each do |comment| %>
        <li><%= comment.comment_description %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
    
<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<%= form_for [@subreddit, @subreddit.posts.build] do |f| %>

    <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div> 

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit "Create new Post" %>
  </div>
<% end %>

<%= link_to "Back", subreddit_path(@subreddit) %>

app/views/profiles/show.html.erb
<h1>User Profile:</h1>
<p>Name: <%= @user.name %></p>

<%= link_to 'Edit Profile', edit_user_registration_path %>
<%= link_to 'Back', root_path %>
<%= link_to 'Create New Subreddit', new_subreddit_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/subreddits/front.html.erb
<h1>Front Page</h1>

<p>Subreddits:</p>
<ul>
        <% @subreddits.each do |subreddit| %>
            <li><%= link_to subreddit.sub_name, subreddit_path(subreddit) %> </li>
        <% end %>
</ul>
<p>Post list here!!</p>

<% if user_signed_in? %>
    <%= link_to 'Profile', profile_path(current_user.name) %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to  'Signup', new_user_registration_path %>
    <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/subreddits/new.html.erb
<h2>Create a new Subreddit</h2>

<%= form_for(@subreddit) do |f| %>
    <% if @subreddit.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@subreddit.errors.count, "error") %>.
        </div>
        <ul>
        <% @subreddit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  <div class="field">
    <%= f.label :sub_name %><br />
    <%= f.text_field:sub_name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "30x10" %>
  </div>

  <div class="actions">
    <%= f.submit "Create new Subreddit" %>
  </div>
<% end %>

app/views/subreddits/show.html.erb
<h1>Subreddit name:<%= @subreddit.sub_name %></h1>
<p>Description: <%= @subreddit.description %></p>
<p>Owner:<%= @subreddit.user.name %></p>

<p>Posts:</p>
<ul>
    <% @subreddit.posts.each do |post| %>
        <li><%= link_to "#{post.title}", "http://#{post.url}" %> - by <%= link_to "#{post.user.name}", profile_path(post.user.name) %> - <%= link_to "Comments", subreddit_post_comments_path(@subreddit, post.id)%>
        <% if current_user == post.user %>
            <%= link_to "Delete Post", subreddit_post_path(@subreddit, post.id), method: :delete %>
        <% end %></li>
    <% end %>
</ul>

<%= link_to "Front", root_path %>
<% if user_signed_in? %>
    <%= link_to 'Profile', profile_path(current_user.name) %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <%= link_to 'New Post', new_subreddit_post_path(@subreddit) %>
    <% if current_user == @subreddit.user %>
        <%= link_to 'Delete Subreddit', subreddit_path(@subreddit), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
<% end %>